name: 'Publish to Itch.io with Butler'
description: 'Automatically sets up Butler and provides a simple GitHub Action to publish releases to Itch.io'
author: 'Oval Tutu'
branding:
  color: red
  icon: send

inputs:
  api-key:
    description: 'Butler API key'
    required: true
  channel:
    description: 'itch.io channel name. For example: android, html, linux, osx or windows'
    required: true
  itch_user:
    description: 'itch.io user name'
    required: true
  itch_game:
    description: 'itch.io game name'
    required: true
  package:
    description: 'The directory or file to upload'
    required: true
  version:
    description: 'game version'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Download butler (windows only)
      env:
        BUTLER_API_KEY: ${{ inputs.api-key }}
      shell: bash
      run: |
        # Hardcoded to Windows builds
        BUTLER_PLATFORM="windows-amd64"
        BUTLER_EXEC="butler.exe"
        mkdir ./tools 2>/dev/null || true
        pushd tools
          curl -sSLfo ./butler.zip "https://broth.itch.zone/butler/${BUTLER_PLATFORM}/LATEST/archive/default"
          unzip butler.zip
          chmod +x ./${BUTLER_EXEC}
        popd
        ./tools/${BUTLER_EXEC} -V

    - name: Upload to itch.io (windows only)
      env:
        BUTLER_API_KEY: ${{ inputs.api-key }}
      shell: bash
      run: |
        BUTLER_EXEC="butler.exe"
        versionArgument=""
        if [ -n "${{ inputs.version }}" ]; then
          versionArgument="--userversion ${{ inputs.version }}"
        fi
        ./tools/${BUTLER_EXEC} push \
          "${{ inputs.package }}" \
          ${{ inputs.itch_user }}/${{ inputs.itch_game }}:${{ inputs.channel }} ${versionArgument}
